apiVersion: v1
kind: Service

metadata:
  name: nodeserver
spec:
  selector:
    app: nodeserver
  type: LoadBalancer # ClusterIP | NodePort 
  ports:
  - name: nodeserver-service
    port: 80
    targetPort: 8000
    protocol: TCP
    # nodePort: 30000 - 32767